### ISSUE TITLE
docker container fails to start

### ISSUE THREAD

**Issue by machzqcq** [FOSSEE/online_test#170]
- Checkout source code master
- Step into online_test directory and execute `docker build -t yaksha:v1 -f Dockerfile .`
- `docker images` will show the docker image successfully created
- `docker run -d -p 8001:8001 -p 53579:53579 yaksha:v1` - start the server

**Actual:** The container immediately dies. `docker logs -f <container_id>` shows the following error stack trace. `Traceback (most recent call last):
  File "/src/yaksh/code_server.py", line 51, in <module>
    from tornado.ioloop import IOLoop
ImportError: No module named tornado.ioloop`  

**Expected:** Server starts without error inside container and able to access the web ui on :8001

**Comment by adityacp** [comment]
Thanks for pointing this out. The ```code_server.py``` now also needs Tornado to be able to run successfully.
Please save this as your Dockerfile and follow the steps again

FROM debian:8.2
MAINTAINER FOSSEE <pythonsupport@fossee.in>

# Update Packages and Install Python & net-tools
RUN apt-get update && apt-get install -y python net-tools python-pip && pip install tornado

# Copy the project folder from host into container
COPY ./yaksh /src/yaksh

WORKDIR /src

# Run Yaksh code server
CMD ["python", "-m", "yaksh.code_server"]

**Comment by machzqcq** [comment]
Thanks! That fixed the docker container coming up, however accessing http://localhost:8001 throws this server stack trace with 501


`pmacharl$ docker logs -f 387
172.17.0.1 - - [31/Dec/2016 00:59:21] code 501, message Unsupported method ('GET')
172.17.0.1 - - [31/Dec/2016 00:59:21] "GET / HTTP/1.1" 501 -
172.17.0.1 - - [31/Dec/2016 00:59:21] code 501, message Unsupported method ('GET')
172.17.0.1 - - [31/Dec/2016 00:59:21] "GET /favicon.ico HTTP/1.1" 501 -
`

**Comment by adityacp** [comment]
Good to know that your docker instance is up and running.
Are you running the Django test server on your local machine using ```python manage.py runserver```? If yes, please access the link http://localhost:8000/exam, If not, we will need to know a bit about your server setup to help you further.

**Comment by machzqcq** [comment]
Now when I try to build the server with the above Dockerfile, it results in this (tried at least 5 times over the day). Looks like not an app issue, but still wanted to confirm if you face the same ?


`Err http://httpredir.debian.org/debian/ jessie/main python-ndg-httpsclient all 0.3.2-1
  Error reading from server. Remote end closed connection [IP: 5.153.231.35 80]
Get:103 http://httpredir.debian.org/debian/ jessie/main python-openssl all 0.14-1 [81.1 kB]
Get:104 http://httpredir.debian.org/debian/ jessie/main python-urllib3 all 1.9.1-3 [55.4 kB]
Get:105 http://httpredir.debian.org/debian/ jessie/main python-requests all 2.4.3-6 [204 kB]
Get:106 http://httpredir.debian.org/debian/ jessie/main python-setuptools all 5.5.1-1 [242 kB]
Get:107 http://httpredir.debian.org/debian/ jessie/main python-pip all 1.5.6-5 [114 kB]
Get:108 http://httpredir.debian.org/debian/ jessie/main python-pyasn1 all 0.1.7-1 [49.3 kB]
Get:109 http://httpredir.debian.org/debian/ jessie/main python-wheel all 0.24.0-1 [47.5 kB]
Get:110 http://httpredir.debian.org/debian/ jessie/main rename all 0.20-3 [12.4 kB]
Fetched 71.7 MB in 17s (4202 kB/s)
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/n/ndg-httpsclient/python-ndg-httpsclient_0.3.2-1_all.deb  Error reading from server. Remote end closed connection [IP: 5.153.231.35 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get update && apt-get install -y python net-tools python-pip && pip install tornado' returned a non-zero code: 100`

**Comment by maheshgudi** [comment]
Is fixed with PR #379.
