### ISSUE TITLE
Add mathjax by default

### ISSUE THREAD

**Issue by prabhuramachandran** [FOSSEE/online_test#196]
Should make it easy to add formulae to questions.

**Comment by maheshgudi** [comment]
So there are two ways this can be done. One and the most recommended way of doing this is by loading the MathJax js from MathJax CDN. 

The other is to clone their Github repo and add it in our repo.

**Comment by prabhuramachandran** [comment]
CDN is fine as users are on the internet when they visit yaksh anyway.
