### ISSUE TITLE
Migration Files: Naming convention and Renaming Issues

### ISSUE THREAD

**Issue by ankitjavalkar** [FOSSEE/online_test#278]
* As suggested by @maheshgudi we need to set a naming convention for migration files and move on with our lives.
* Also another purpose of this issue is to inform that renaming a migration after it has already been created using the ```makemigrations``` command is risky as Django will then be unaware if the migration has been applied or not. (Please see http://stackoverflow.com/questions/30425912/is-it-safe-to-rename-django-migrations-file)
* Hence we cannot rename the existing migrations
---
I propose the following convention:
1. Always add all migrations file in the last commit.
1. Retain the ID order of the migration (for eg. 0006 in ```0006_auto_20170401_0632```)
1. Add the first 7 digits of the commit ID of the previous commit (the commit ID before the migration file commit) that contains the actual changes, not the commit ID of the migration file. (for eg. 0006_a9e787c)
1. Add the name of the feature in small case and using underscores (for eg. 0006_a9e787c_new_migration_feature.py)

So the complete file name will be 0006_a9e787c_new_migration_feature.py

**Comment by prabhuramachandran** [comment]
Do we really need migrations for every PR?  Can we not just have migrations from one public release to the next?  This will make it easier for development while making deployment fairly straightforward as well.

**Comment by ankitjavalkar** [comment]
@prabhuramachandran I agree. Waiting for other's feedback.

**Comment by adityacp** [comment]
I also agree

**Comment by maheshgudi** [comment]
I agree.

**Comment by adityacp** [comment]
I think if we don't have migrations in the PRs then tests might fail. This scenario happened earlier where test were failing because migrations were not present.

**Comment by ankitjavalkar** [comment]
Created an issue #281 for the problem pointed out by @adityacp

**Comment by maheshgudi** [comment]
Closes with #282
