### ISSUE TITLE
Deactivated Quizzes show up in 'Enrolled Courses' page

### ISSUE THREAD

**Issue by ankitjavalkar** [FOSSEE/online_test#308]
- Enrolled Courses should explicitly show a Course (which the student has already enrolled for) but keep it in disabled state
- Home page (where un-enrolled courses show up) will not show the deactivated courses at all.
- The Quizzes, Answerpapers, etc should not be visible at all.

**Comment by prathamesh920** [comment]
Even if the course is disabled, a student should be able to see his answer papers. Yes should not be able to attempt a quiz. In short the student should be able to do GET.
