### ISSUE TITLE
Docker for Windows

### ISSUE THREAD

**Issue by prathamesh920** [FOSSEE/online_test#393]
Should work on windows as well.
Python modules should use for copying, deleting etc. instead of bash commands.

Edit:
Use inbuilt python modules:
- Copying function
- Removing files
- Creating directories [Done]

Superuser support:
1. Check the system OS using python libraries
1. Append a ```sudo``` or relevant command to every execution step

**Comment by ankitjavalkar** [comment]
Docker does not seem to be as straight forward on Windows as it is on Linux. This is a wontfix for now. Closing
