### ISSUE TITLE
Problem with course status update

### ISSUE THREAD

**Issue by prathamesh920** [FOSSEE/online_test#439]
Course status is updated only if a student clicks ```Next Unit```!
But at the same place we have ```Home``` option!

Now if we have two modules with a quiz in each with single attempt then if after 1st quiz a student clicks on Home instead of Next then the student is stuck!
Because he cannot go to Next module because first one is not complete.
And he cannot go to that Next button again in the current module as quiz has only one attempt!
So cannot proceed further.

**Comment by adityacp** [comment]
Fixed in #436.
Now there is no `Home` button after quiz completion only `Next ` button is available.
