### ISSUE TITLE
Module get status method 

### ISSUE THREAD

**Issue by prathamesh920** [FOSSEE/online_test#440]
The get status method of learning module should check if the module contains unit or not.
If no unit in a module then the return status should be ```completed``` for that module

**Comment by prathamesh920** [comment]
But we cannot do that as Module and Units are not linked with the user.
Even Module and Units check the status using CourseStatus, where user and course are linked!
For now we need a method only, may be we can have an attribute in CourseStatus which gives the Boolean state.

**Comment by adityacp** [comment]
I am saying we can do something similar to check_prerequisite which we have in module and unit so that moderator can change it and consider only those units and modules which has check_status True. We can discuss about it.

**Comment by adityacp** [comment]
Fixed in #438
