### ISSUE TITLE
Attendance system

### ISSUE THREAD

**Issue by prathamesh920** [FOSSEE/online_test#441]
So for some cases we need the following:
Now, we enroll students in a course, and the enrolled student can attempt quiz from any location.
There is no check on his physical presence!
In case we conduct a quiz at a given location and it is mandatory for the student to be present at that location,
Then there should be a way by which we can allow only those students who are present.

**Comment by NeoHimu** [comment]
I have made an android app for the same. The app generates a QR code and Prof. can share the QR code on the projector. Students can scan the QR code to mark their presence. This QR code validity will be decided by the Prof. i.e. he has two buttons : START and STOP. One has to scan the QR code between these time stamps. Time difference between START and STOP is generally 20-30 seconds. Anyone opening any app with camera permission to take a picture of QR code will be reported by the app to the Prof. In this way, leaking of QR code outside the venue is prohibited. We can integrate the mobile app with this app.

**Comment by NeoHimu** [comment]
You can find the app source code here : [https://github.com/NeoHimu/Attendi](url)
