### ISSUE TITLE
Link to Production Deployment Guide document gives a 404

### ISSUE THREAD

**Issue by Ram-N** [FOSSEE/online_test#443]
In *README.md*:

`
This is a Quickstart guide to help users set up a trial instance. If you wish to deploy Yaksh in a production environment here is a Production Deployment Guide.
`

That link is broken.

**Comment by adityacp** [comment]
Thank you for letting us know about the broken URL. We will fix the README.rst.
You can try https://github.com/FOSSEE/online_test/blob/master/README_production.rst for production deployment
