### ISSUE TITLE
Additions and fixes code server

### ISSUE THREAD

**Issue by adityacp** [FOSSEE/online_test#454]
1. Question should support yaml, yml and without zip yaml upload
2. Check stdio with new line and spacing to make it robust
3. Tags in design question paper.
4. Formatting of test cases should be proper.

**Comment by maheshgudi** [comment]
I would request everyone to refrain from adding multiple issues under one ticket. 
Closing this issue as part of its are now fixed as mentioned below -
1. Closed with #496 
2. Created a separate issue 
3. Closed with #489 
4. Very ambiguous. Better to file a separate issue.
