### ISSUE TITLE
Allow users to change email addresses in their profiles

### ISSUE THREAD

**Issue by ankitjavalkar** [FOSSEE/online_test#479]
- Users currently are unable to change their email addresses.
- Verification emails need to be triggered once the email is changed

**Comment by maheshgudi** [comment]
I am not sure if changing emails should be allowed. Email ids are unique identifiers and letting users change it at will shall end up costing us in ways unknown to us. Instead I suggest, we can have users add a **secondary email address**. Change of email addresses for accidental mistakes while registering can be dealt with manually.

**Comment by ankitjavalkar** [comment]
Closing this issue as a #WontFix ticket
