### ISSUE TITLE
Error while installing in Mac OS

### ISSUE THREAD

**Issue by ppshobi** [FOSSEE/online_test#485]
`$ pip install -r ./requirements/requirements-py3.txt`

while running the above command I am getting the following error

> Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-102w30z3/mysqlclient/

**Comment by maheshgudi** [comment]
Hi, I believe this is because of a library missing for MySQL. Just to be sure can you post the full traceback?

**Comment by ppshobi** [comment]
> Collecting pytest (from -r ./requirements/requirements-codeserver.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/11/c4/cfb5f51f401cd54bbaaacff530c96827422a29dca2683ff314e4938444c9/pytest-3.6.2-py2.py3-none-any.whl
> Collecting python-decouple (from -r ./requirements/requirements-codeserver.txt (line 2))
>   Using cached https://files.pythonhosted.org/packages/9b/99/ddfbb6362af4ee239a012716b1371aa6d316ff1b9db705bfb182fbc4780f/python-decouple-3.1.tar.gz
> Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from -r ./requirements/requirements-codeserver.txt (line 3)) (1.11.0)
> Requirement already satisfied: requests in /usr/local/lib/python3.6/site-packages (from -r ./requirements/requirements-codeserver.txt (line 4)) (2.18.4)
> Collecting tornado==4.5.3 (from -r ./requirements/requirements-codeserver.txt (line 5))
>   Using cached https://files.pythonhosted.org/packages/e3/7b/e29ab3d51c8df66922fea216e2bddfcb6430fb29620e5165b16a216e0d3c/tornado-4.5.3.tar.gz
> Collecting psutil (from -r ./requirements/requirements-codeserver.txt (line 6))
>   Using cached https://files.pythonhosted.org/packages/51/9e/0f8f5423ce28c9109807024f7bdde776ed0b1161de20b408875de7e030c3/psutil-5.4.6.tar.gz
> Collecting nose==1.3.7 (from -r ./requirements/requirements-codeserver.txt (line 7))
>   Using cached https://files.pythonhosted.org/packages/15/d8/dd071918c040f50fa1cf80da16423af51ff8ce4a0f2399b7bf8de45ac3d9/nose-1.3.7-py3-none-any.whl
> Collecting invoke==0.21.0 (from -r ./requirements/requirements-common.txt (line 2))
>   Using cached https://files.pythonhosted.org/packages/1e/81/f8bf4630a3b78985de59201e17a2ba155d686c492fd0370ac9b5b5e17cb5/invoke-0.21.0-py3-none-any.whl
> Collecting django==1.10 (from -r ./requirements/requirements-common.txt (line 3))
>   Using cached https://files.pythonhosted.org/packages/4b/4c/059f68d8f029f7054e4e6bb0b1ed2fde7f28d07a3727325727d5a95ae1b8/Django-1.10-py2.py3-none-any.whl
> Collecting django-taggit==0.18.1 (from -r ./requirements/requirements-common.txt (line 4))
>   Using cached https://files.pythonhosted.org/packages/cb/c7/6efef8994fe030246e601e89698a82c38e1d65dec90bb1f686ebc596c725/django_taggit-0.18.1-py2.py3-none-any.whl
> Collecting pytz==2016.4 (from -r ./requirements/requirements-common.txt (line 5))
>   Using cached https://files.pythonhosted.org/packages/ae/cf/a7442138ad899a7587489641a8923f1e640cafc2d6ffe4e79e5d15cc5b3e/pytz-2016.4-py2.py3-none-any.whl
> Collecting python-social-auth==0.2.19 (from -r ./requirements/requirements-common.txt (line 6))
>   Using cached https://files.pythonhosted.org/packages/93/0d/88ceecd3a6fbe5210a5c53e24edb43c687162fdc9c73b9eaeef26999279b/python_social_auth-0.2.19-py3-none-any.whl
> Collecting selenium==2.53.6 (from -r ./requirements/requirements-common.txt (line 7))
>   Using cached https://files.pythonhosted.org/packages/3f/f8/e46684764161fee7b7d2e0fd9b82d56915438b68e498181dc45183643c82/selenium-2.53.6-py2.py3-none-any.whl
> Collecting coverage (from -r ./requirements/requirements-common.txt (line 8))
>   Using cached https://files.pythonhosted.org/packages/a3/7e/c94c21d643bfe7017615994df7b52292a33c8dcf36a6f694af110594edba/coverage-4.5.1-cp36-cp36m-macosx_10_12_x86_64.whl
> Collecting ruamel.yaml==0.15.23 (from -r ./requirements/requirements-common.txt (line 9))
>   Using cached https://files.pythonhosted.org/packages/a7/7d/d77b8df7cb7616d87ae1465d1a9dd7f090ecc0ceec58ca22181e86cb9359/ruamel.yaml-0.15.23.tar.gz
> Collecting markdown==2.6.9 (from -r ./requirements/requirements-common.txt (line 10))
>   Using cached https://files.pythonhosted.org/packages/29/82/dfe242bcfd9eec0e7bf93a80a8f8d8515a95b980c44f5c0b45606397a423/Markdown-2.6.9.tar.gz
> Collecting mysqlclient==1.3.9 (from -r ./requirements/requirements-py3.txt (line 2))
>   Using cached https://files.pythonhosted.org/packages/db/f5/c8e1657985c31dda16e434edf5257c31572fa5faacd7e48b1618390e4b18/mysqlclient-1.3.9.tar.gz
>     Complete output from command python setup.py egg_info:
>     /bin/sh: mysql_config: command not found
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/7w/nm1j7rp507qfpgfns1f3by040000gn/T/pip-install-6na895fb/mysqlclient/setup.py", line 17, in <module>
>         metadata, options = get_config()
>       File "/private/var/folders/7w/nm1j7rp507qfpgfns1f3by040000gn/T/pip-install-6na895fb/mysqlclient/setup_posix.py", line 44, in get_config
>         libs = mysql_config("libs_r")
>       File "/private/var/folders/7w/nm1j7rp507qfpgfns1f3by040000gn/T/pip-install-6na895fb/mysqlclient/setup_posix.py", line 26, in mysql_config
>         raise EnvironmentError("%s not found" % (mysql_config.path,))
>     OSError: mysql_config not found
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7w/nm1j7rp507qfpgfns1f3by040000gn/T/pip-install-6na895fb/mysqlclient/

**Comment by adityacp** [comment]
I guess in your system you don't have MySQL installed. You can try installing MySQL by the command brew install mysql. If the error still persists you can comment here.

**Comment by maheshgudi** [comment]
Closing this issue for lack of response
