### ISSUE TITLE
Grade User answer rendering incorrectly recognises expressions as code

### ISSUE THREAD

**Issue by ankitjavalkar** [FOSSEE/online_test#511]
Answer rendering in Grade user page is done with ```<pre>``` and ```<code>``` tags this causes it to recognise certain expressions as HTML tags Example `0<a` is assumed to be the HTML <a> tag

**Comment by kumanna** [comment]
Will something like this help?

https://stackoverflow.com/questions/11306669/django-template-escaping

**Comment by ankitjavalkar** [comment]
Yes, this issues is not caused due to existing ```<pre>``` or ```<code>``` tags. Thank you for the link.
