### ISSUE TITLE
View Lessons/Quizzes/Exercises - Hover cursor pointer 

### ISSUE THREAD

**Issue by TummanapallyAnuraag** [FOSSEE/online_test#521]
In the Overall Course Progress page, 
hovering over "View Lessons/Quizzes/Exercises" doesn't turn the mouse pointer.
![bug](https://user-images.githubusercontent.com/21244258/43581013-f99da17c-9674-11e8-958d-25b767c84492.png)

**Comment by adityacp** [comment]
Fixed in #652
