### ISSUE TITLE
Add a 'Report This' or 'Provide Feedback Button'

### ISSUE THREAD

**Issue by ankitjavalkar** [FOSSEE/online_test#555]
Currently there is no way for a student to communicate with Course creators, teachers, moderators and administrators.

Need to add a **Report This Issue** or **Provide Feedback Button** that will send the following information back to the Moderator/System Administrator:
- Student Name and Info
- Course Info / Module Info / Lesson Info / Quiz Info / Question Info where the issue has occurred
- Message / Comment to allow student to describe the issue

This report will be exchanged using a Message/Inbox section that allows bidirectional communication between the Students and Moderators.

**Comment by NeoHimu** [comment]
Along with above things, the instructor should get notified via mail. Mailing is required because instructor will not be always logged in to the portal.

**Comment by CruiseDevice** [comment]
#690 closes this.
