### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by Prashanthselva** [FOSSEE/online_test#58]
i used "pip install yaksh" it throws a error
Could not find a version that satisfies the requirement yaksh (from versions: )
No matching distribution found for yaksh
please reply asap

**Comment by ankitjavalkar** [comment]
Will update the ```setup.py``` file with the new app name and push the changes soon.

**Comment by Prashanthselva** [comment]
I am unable to display list of questions when i run app as a user but am able to add questions in admin
the problem is there is no link to questions which should be displayed in user side (path: yaksh/static/yaksh/js)...
please can i know when you will update setup.py file and new app

**Comment by ankitjavalkar** [comment]
In order for your User to be able to see the Questions in the Interface (the views, not the admin), the User must be added to a group called ```moderator```
You can create a group using the Admin interface (Home > Auth > Groups)
1. Hit 'Add Group'
1. Choose all permissions that start with 'yaksh | ...'
1. Save it as ````moderator```
1.  You will now be able to see this group in 'Group' section in the User Page (Home > Auth > User > $your_user_name)
1. Choose that group and save it.
1. Log into the Interface again

**Comment by ankitjavalkar** [comment]
Alternatively, we are in the process of adding a demo database (as a fixture) which contains a default admin, student and teacher along with a few demo questions and a quiz.
This will be available once the PR #59 is merged.
Once it is available you can add it to your database using ```python manage.py loaddata yaksh/fixtures/demo_fixtures.json```

**Comment by kamleshchauhan** [comment]
I am getting the same error: 
i used "pip install yaksh" it throws a error
Could not find a version that satisfies the requirement yaksh (from versions: )
No matching distribution found for yaksh

**Comment by ankitjavalkar** [comment]
@kamleshchauhan @Prashanthselva We have pushed the package to PYPI today. You can try ```pip install yaksh``` again.
Alternatively you can also try installing from the github repo using;
```pip install git+https://github.com/FOSSEE/online_test.git@master```

**Comment by ankitjavalkar** [comment]
@kamleshchauhan @Prashanthselva Will close this issue for now.
