### ISSUE TITLE
 [Production Issue] Fixes in new UI

### ISSUE THREAD

**Issue by adityacp** [FOSSEE/online_test#581]
Course Details Page UI issues:- 
- [x] Course details page does not have proper table alignment for enrolled students section. 
- [ ] Same issue as above in send mail section of the course details page.
- [x] Student name is shown in the `Current unit` column in view course status page.
- [x] No need of `Export to CSV` button in the course status page.
- [x] Hovering on the email in course status page does not show the tooltip properly.

Courses page UI issues:-
- [x] Teachers added to the course does not show properly. Checkbox alignment is not proper.

Login related UI fixes:-

- [ ] Change password is showing Django internal templates and not the override templates. Same for forgot password.
- [ ] After changing profile, reloading gif is not showing up.

Student Dashboard:- 

- [x] Unable to see download course button on student dashboard

**Comment by CruiseDevice** [comment]
Adding screenshots related to the above issues here for reference:

* Student name is shown in the `Current unit` column in view course status page. [Screenshot below]

![image](https://user-images.githubusercontent.com/10258150/52993802-7b6d8280-343b-11e9-9da2-f52d324e03ee.png)

* Course details page does not have proper table alignment for enrolled students section [Screenshot below]

![image](https://user-images.githubusercontent.com/10258150/52993870-b374c580-343b-11e9-9269-468028d71fd0.png)

**Comment by CruiseDevice** [comment]
> * Hovering on the email in course status page does not show the tooltip properly.

Already handled in Jquery update PR #552.

**Comment by CruiseDevice** [comment]
> * Same issue as above in send mail section of the course details page.

@adityacp I think there is no problem with the send_email template. Can you please reproduce the error and post the screenshot here.

**Comment by NeoHimu** [comment]
>     * Change password is showing Django internal templates and not the override templates. Same for forgot password.

unable to reproduce the issue.. working fine on my local system. @ankitjavalkar @prathamesh920

**Comment by adityacp** [comment]
Fixed in #652
