### ISSUE TITLE
Add/Edit Question Interface (UI Change)

### ISSUE THREAD

**Issue by adityacp** [FOSSEE/online_test#583]
Add text editor for question description in Add question interface to avoid using HTML tags.

**Comment by ankitjavalkar** [comment]
I'd suggest that you add it in a few more places:
- Quiz Instructions
- Module Description
- Lesson Description

**Comment by ankitjavalkar** [comment]
Taking this a step forward, can you check if this can be made a widget/form component that we can use in multiple places to respect the DRY principle?

**Comment by adityacp** [comment]
I am not sure if this can be made as a form widget since this completely JS library.

**Comment by CruiseDevice** [comment]
@adityacp  https://github.com/aljosa/django-tinymce Can this be used as widget?

**Comment by adityacp** [comment]
I saw the same package. I am not sure if we should add an extra dependency.

**Comment by ankitjavalkar** [comment]
@adityacp can we use the same source code as the django-tinymce plugin?

**Comment by adityacp** [comment]
Fixed in #652
