### ISSUE TITLE
Change the production URL : Difficult to remember for common users

### ISSUE THREAD

**Issue by NeoHimu** [FOSSEE/online_test#593]
Current url : yaksh.fossee.in
My suggestion : yaksh.in 

URL should always be something that a common users can easily remember. 'Yaksh' is already a complex name to remember and to pronunciate for non-Indian (or millennials and generation Z Indian) users. And our large part of users are millennials and generation Z.  This extra 'fossee' in the URL is adding more complexity. If we want to give credit to the organization, we can add 'Powered by FOSSEE IIT Bombay' on the homepage and a link to the FOSSEE site.

**Comment by ankitjavalkar** [comment]
Unfortunately, this is an organization level decision. It will be difficult to change at this point due to various reasons.

Kindly use the Issues section to point to issues in the code base.

**Comment by prathamesh920** [comment]
I agree with Ankit as this is quite subjective.
Also, Yaksh is Free and Open Source, so anyone deploying it will have the URL of their choice.
People barely read the URL or try to remember, its always a link for them to click on or copy paste or very rarely type!
Hence closing.
