### ISSUE TITLE
Fix UI/UX inside course page in student dashboard

### ISSUE THREAD

**Issue by adityacp** [FOSSEE/online_test#618]
- [ ] Make the sidebar proper and ability to hide.
- [ ] Show course and module information properly.

**Comment by sarveshwaranj** [comment]
Hi How to add courses and Learning module since I cant see anything in admin page

**Comment by ankitjavalkar** [comment]
This issue has been created to enhance the UI and/or fix bugs in the UI. 

Please read the [documentation](http://yaksh.readthedocs.io/), link is available in the README file. In case you are having issues with the instance of yaksh already hosted at yaksh.fossee.in, please drop us an email at pythonsupport@fossee.in
