### ISSUE TITLE
Error on first server run

### ISSUE THREAD

**Issue by johnsmith1232541** [FOSSEE/online_test#788]
I followed the guide on starting up the server for the first time, however I keep getting this error upon login: 
"no such table: notifications_plugin_notification"

I'm using last release 0.23.0

**Comment by adityacp** [comment]
Please run the command `python3 manage.py makemigrations notifications_plugin` and then `python3 manage.py migrate`. This should resolve the issue.

**Comment by johnsmith1232541** [comment]
Thank you, that did solve it. Somehow I was under the impressino that `python manage.py makemigrations` would make them for all apps, but aparently not.
